V1.7.9 patchset
coreos/kubernetes pull request #174
Opened 2017-10-19 13:20 UTC by squat

Dev tests are passing. Carries patches from 1.7.8, including Calico 1.11.0.

cc @s-urbaniak @aaronlevy

2017-10-23 06:07 UTC, s-urbaniak commented on cluster/images/hyperkube/Makefile
> +	chmod +x ${TEMP_DIR}/cni-bin/bin/calico
As discussed last week: we should make sure that the flannel binaries are in sync with https://github.com/coreos/tectonic-installer/blob/master/config.tf#L69.

2017-10-23 06:12 UTC, s-urbaniak requested changes
I have no objections modulo the flannel binaries sync. We could take this release as the precedence to:

1. sync the flannel binaries with the expected ones in installer's 1.7.9
2. In addition start shipping the `portmap` plugin

2017-10-23 19:47 UTC, aaronlevy commented
cc @dghubble - do you know if there are recommended calico-CNI versions for v1.7.x?

2017-10-23 19:54 UTC, dghubble commented
Calico docs still show cniVersion 0.1.0, so I don't think we'll find a recommendation there. https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml. The 2.6.x plugins correspond to Kubernetes v1.7.x though.

2017-10-24 10:33 UTC, s-urbaniak approved these changes

2017-10-24 12:25 UTC, squat commented
Dev tests succeeded. Running one more test locally and then merging.

2017-10-24 12:51 UTC, squat commented
Clusters are coming up happily. Merging.

2017-10-24 12:52 UTC, merged